name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.2
      - name: Install dependencies
        run: poetry install
      - name: Static type checking
        run: make type
      - name: Lint
        run: make lint
      - name: Formatting
        run: make format-check
      - name: Unit tests
        run: make test